- hosts: all
  become: true
  gather_facts: False
  user: ubuntu
  vars_files:
  - "vars/main.yml"

  tasks:
  - name: ' remove consul local.snapshot'
    raw:  rm -rf  /var/consul/serf/local.snapshot